### ISSUE TITLE
.libs/libgumbo.so not generated

### ISSUE THREAD

**Issue by Bekt** [google/gumbo-parser#246]
The C library installation doesn't seem to give any errors. However, .libs/libgumbo.so does not exist.

https://github.com/google/gumbo-parser/blob/2db1796396f0c90a20a06466abca179fcb65be57/setup.py#L11

Because of this I am getting the following error when I try to import gumbo in python3. Any suggestions? I am on Mac OSX 10.9 with gcc --version:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix

> import gumbo
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gumbo-0.9.1-py3.3.egg/gumbo/gumboc.py", line 32, in <module>
    os.path.dirname(__file__), '..', '..', '.libs', 'libgumbo.so'))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ctypes/__init__.py", line 431, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gumbo-0.9.1-py3.3.egg/gumbo/../../.libs/libgumbo.so, 6): image not found

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gumbo-0.9.1-py3.3.egg/gumbo/__init__.py", line 33, in <module>
    from gumbo.gumboc import *
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gumbo-0.9.1-py3.3.egg/gumbo/gumboc.py", line 36, in <module>
    os.path.dirname(__file__), 'libgumbo.so'))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ctypes/__init__.py", line 431, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/gumbo-0.9.1-py3.3.egg/gumbo/libgumbo.so, 6): image not found

**Comment by nostrademons** [comment]
A number of Mac/Windows shared library fixes went into the Python bindings in 0.9.3.  Do they fix this?

**Comment by Bekt** [comment]
I haven't used gumbo in a while, maybe somebody else can confirm. Should I close this?

**Comment by nostrademons** [comment]
Yeah, I think this is fixed now, given that we now have TravisCI tests on Mac and recent fixes went in on this area.
